### ISSUE TITLE
Manage unsupported type in url of repository

### ISSUE THREAD

**Issue by ragingwind** [rhiokim/flybook#11]
I faced the issue that redirecting github page doesn't work when it uses of git+https url in package.json

```
  "repository": {
    "type": "git",
    "url": "git+https://github.com/seouljs/seouljs.github.io.git"
  },
```

flybook generates this elements below:

```
<a href="git+https://github.com/seouljs/seouljs.github.io.git">Github</a>
```

**Comment by rhiokim** [comment]
It'll be fixed with next release. thx

specification of npm `repository` -  https://docs.npmjs.com/files/package.json#repository

**Comment by ragingwind** [comment]
FYI,  `npm init` command generates a package.json with git+url as a member of repository when git has been already initialized before. You can reproduce it as follow steps below

- create a project on github
- run the script from github
```
echo "# test1" >> README.md
  git init
  git add README.md
  git commit -m "first commit"
  git remote add origin https://github.com/ragingwind/test1.git
  git push -u origin master
```
- run `npm init`
```
{
  "name": "nm4",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/ragingwind/test1.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/ragingwind/test1/issues"
  },
  "homepage": "https://github.com/ragingwind/test1#readme"
}
```

**Comment by rhiokim** [comment]
New version(1.4.2) flybook was released.

Flybook works with a few of `repository` definitions of npm's specification 
Both of shorten name and object type are supported

shorten `rhiokim/flybook`, `bitbucket:rhiokim/flybook` and `gitlab:rhiokim/flybook` and
as you mention like below too
```
"repository": {
  "url": "git+https://~~",
  "type": "git"
}
```
