### ISSUE TITLE
GNB 영역의 BI(제목), Home, Github 링크가 예상대로 만들어지지 않는 현상

### ISSUE THREAD

**Issue by djkeh** [rhiokim/flybook#13]
* 사용환경: Windows 7, Git Bash, Chrome
* node 버젼: 6.10.0
* npm 버젼: 3.10.10
* yarn 버젼: 0.24.5
* flybook 버젼: 1.4.1
* 설치 패키지: yarn, flybook, gh-pages
* 증상: flybook으로 `gh-pages` 브랜치에 정적페이지 생성 후 결과물을 확인해보면 GNB 영역의 링크들이 예상대로 만들어지지 않습니다.
  * BI
    * expected: `https://djkeh.github.io/project`
    * actual: `https://djkeh.github.io/`
  * Home
    * expected: `https://djkeh.github.io/project`
    * actual: `https://djkeh.github.io/`
  * Github
    * expected: `https://github.com/djkeh/project`
    * actual: 링크가 생성되지 않음
* 재현
  1. yarn init
  2. yarn add flybook -D
  3. `./package.json` 파일에 아래 참고와 같이 "scripts" 커맨드 추가
  4. yarn docs
  5. yarn pages
  6. 깃헙 페이지 사이트로 가서 GNB 확인
* 참고: `package.json`

```json
{
  "name": "project",
  "version": "1.0.0",
  "main": "index.js",
  "repository": "https://github.com/djkeh/project.git",
  "author": "Uno Kim <djkehh@gmail.com>",
  "license": "MIT",
  "scripts": {
      "docs": "flybook docs --outdir=out --silent --font=Noto+Sans --codeStyle=androidstudio --theme=light",
      "pages": "gh-pages -d out"
  },
  "devDependencies": {
    "flybook": "^1.4.1",
    "gh-pages": "^1.0.0"
  }
}
```

위 이슈 확인 부탁드립니다.
감사합니다~

**Comment by rhiokim** [comment]
아! 이 문제였군요.

http://flybook.js.org/basic/configuration.html 이 페이지를 참고해주세요.
자세한 설명이 추가되지 않았지만 위 페이지에 표시된 키와 값을 참조해서 비어있다면 채워주셔야 합니다.

Flybook 은 별도의 `flybook.conf.js`, `flybook.yml` 그리고 `.flybookrc` 와 같은 환경 설정파일 생성을
요구되지 않도록 구현할 계획입니다.

**Comment by rhiokim** [comment]
v1.4.3 에서 좀더 개선되었습니다.

**Comment by djkeh** [comment]
`v1.4.4` 에서 `--prod` 옵션 유무 다시 테스트해 봤습니다.
이제 Git 버튼에는 링크가 잘 달려나오는데요, BI와 Home 버튼에는 링크가 `--prod` 상태와 다르게 나옵니다.
`--prod`는 `package.json` 옵션의 `homepage` 값을 잘 내보내는 것 같은데요, 그냥 내보낼 땐 `/` 이 붙어버리면서 `https://djkeh.github.io/` 까지만 나가는 것 같습니다.

코드를 살펴보니,

https://github.com/rhiokim/flybook/blob/master/libs/main.js#L108

여기서 production 모드가 아닐 때 `/`로 하도록 고정해서 그런 것 같아요.
그래서 `https://user.github.io/project/` 같은 home url을 가진 문서를 내보내면
`https://user.github.io/`라고만 붙는 것 같습니다.

의도하신 부분인 것 같은데, 여기도 production mode랑 똑같이 나가게 하면 어떨까요?

한 번 확인 부탁드릴게요.

###### 추가

이번 업데이트에서 Github 링크의 메뉴 버튼 이름이 `Github` -> `Git`으로 바뀐 것 같네요.
저장소 링크는 Github이 맞으니까 이전 이름이 더 의미에는 맞는 것 같은 느낌도 드는데..
이번에 `Git`으로 바꾸신 이유가 어떤 건지 궁금합니다.

감사합니다~

**Comment by rhiokim** [comment]
`--prod` 는 실 서버 배포시에만 사용되는 옵션으로 보시면 됩니다.. 
`gh-pages` 를 포함해 도메인을 갖은 서비스로 노출될 때 사용하는 옵션이구요.

flybook 이 생성한 정적 파일들이 `gh-pages` 로만 배포되는 것이 아니기 때문이죠.
로컬에서 정적 웹 서버를 띄워서 확인할 경우에는 Home 링크 원격지로 가기 때문에 링크가 깨지게 됩니다.

이 부분은 사용성을 테스트 이후에 좀더 개선할 필요가 있다는 생각이 드네요.

`github` 가 -> `git` 으로 변경된 것은 아직 고민중이긴 하지만 Repository 를 표현하기 위한 수단이였습니다.
bitbucket, gitlab 이 될 수도 있어서 git 으로 변경된 상태입니다.

**Comment by rhiokim** [comment]
이슈는 해결된거 같아 닫습니다.

**Comment by djkeh** [comment]
확인하였습니다. 로컬 테스트 환경을 잊고 있었네요^^ `/`를 준 이유를 잘 이해했습니다.
`Git` 이름도 잘 이해했습니다.
고맙습니다~
