### ISSUE TITLE
기능 질문

### ISSUE THREAD

**Issue by hearimm** [rhiokim/flybook#22]
1. 홈페이지 링크는 어떻게 변경하나요 ? :)
2. 왼쪽 메뉴 리스팅 순서를 변경할 수 있나요?

**Comment by rhiokim** [comment]
네 변경 가능합니다. 

`<docRoot>/toc.yml` 에서 필요에 따라 위치를 변경하시면 됩니다.
단 위치 이외에 key, value 를 변경할 경우 flybook 이 정상 동작 하지 않을 수 있습니다.
