### ISSUE TITLE
페이지 링크

### ISSUE THREAD

**Issue by sculove** [rhiokim/flybook#7]
제의 웹서버 설정이 디렉토리를 보여주는 식으로 되어있어서 알게되었습니다.

```html
<a href="/part1\1-01.intro">1 01.intro</a>
```
/part1\1-01.intro/index.html로 명시 해주면 좋을것 같아요.
마찬가지로 상대경로로 되면 좋겠습니다. #6

**Comment by rhiokim** [comment]
1.0.13 버젼이 릴리즈 되었습니다.
